language: node_js
node_js:
- node
dist: trusty
install:
- npm install
script:
- npm run test
deploy:
  provider: heroku
  app: portfolio-ke
  api_key:
    secure: QNXwxhzcQOYR3UbWLOpLmlt0JfSz9V6QGbxwhWQTAyX/oSOKzsVWWtJaIUz8nawXsRUd4LixUqxu82kTOT/jQHrqvs2GqApjA0Aq1rN6TubBoeRMrGfw2xoyna0Q+sD6MOQ+pzOExlpgxzD6/8ZFoUy0+oTj2JOmYTyNzG8Q4QFIBbMyHhrfTApxftxdvDsKdqbSJRFtWZccslWG8qHlByty1aCW5NqyBZO31KjwdJuT5Jo1MMpwhPQB8H0VwuJcGqykStuH3KGfQWTv0UJE2rCouMpDX67D1Gt8uDDDujH74Yu7MNTHltJNG2XSWW9hKeqZYKXhgwGSOgsOlHse04w7q1YdkJ5qZABbZdAcK18MAcaIhxiifEjlkKhX7/fVJSmeK/fAbDEor+ijn/RZoDoZZUyiwrSHac+5cJMfS+BSKhWFBwFT/zGxdWO7FYA7m/VDB2ulQdiMkonZyyurIiW4PBr6H5oAPapROIIj4wqW2Ww7s07i/Ltl7feoKo4WrixU8duKgVsyU1i0e2tZCs0jB9dmx5InfkdmtUxmWmBoDW5PLC8MZXPpaWTo8bVuWVAj4ab69nN/8nCJ8NICZdc0DxcalO4ehh7B9YaAqbnTzZ8PPOQaPexBwgydnh6pe6n6Zn1QPcrbBuRpwvoQzbJkx0z0X6wr2fR0MyME1Dw=
